var gulp = require('gulp'),
    less = require('gulp-less'),
    cssmin = require('gulp-minify-css'),
    htmlmin = require('gulp-htmlmin');
var through = require('through2');
var concat = require('gulp-concat');
const minify = require('gulp-minify');
var uglify = require('gulp-uglify');
const cssnano = require('gulp-cssnano');
const cleanCSS = require('gulp-clean-css');
